### ISSUE TITLE
Doc bug - Works with Angluar, just not Ripple or hosted apps in Ionic LiveReload

### ISSUE THREAD

**Issue by Chuxel** [Azure/azure-mobile-apps-cordova-client#2] opened 2016-02-25 23:55 UTC
The limitations mentioned in this documentation make it appear that Angluar based apps won't work with the plugin.  That would be a massive problem if so.  However, the real issue appears to be specifically when using Ripple or something like Ionic's LiveReload where the content is hosted instead of local that causes problems.

This should be resolved as it has come up in a number of customer conversations.

**Comment by adrianhall** [comment] 2016-02-28 11:34
Thanks @Chuxel - the problem is a little deeper than you expect.  It definitely occurs in Ripple and Ionic LiveReload (as you mentioned).  However, it will be resolved by the time we would be able to update the documentation, so we'll just leave it as is.

**Closed by adrianhall** 2016-02-28 11:34 UTC

**Comment by sjaanus** [comment] 2016-08-12 12:59
Is this solved? Still does not work for me. Any workaround?

**Comment by adrianhall** [comment] 2016-08-12 16:43
Should work with the latest RC of the plugin.
