### ISSUE TITLE
WindowsAzure undefined when called in ionic

### ISSUE THREAD

**Issue by digish777** [Azure/azure-mobile-apps-cordova-client#63] opened 2018-07-26 03:22 UTC
Hi,
I installed the  cordova-plugin-ms-azure-mobile-apps, but was found to be undefined in ionic.

 constructor(public navCtrl: NavController, public plt: Platform) {
    this.plt.ready().then((readySource) => {
      console.log('Platform ready from', readySource);
      var WindowsAzure: any;
      var client = new WindowsAzure.MobileServiceClient('https://xyz.azurewebsites.net', 'xyz');
      client.login('aad')
        .then(function (result) {
        
        });
    });
  }

Why is WindowsAzure undefined?

**Comment by jaelim-ms** [comment] 2018-07-26 18:59
Have you followed this [documentation](https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/first-steps/getting-started-with-ionic?view=toolsforcordova-2015&viewFallbackFrom=toolsforcordova-2017)? If yes, then can you give me more details about your error such as error messages?

**Comment by wohlbier** [comment] 2018-07-31 01:28
This issue is timely as I ran into a similar error and am having difficulty finding up to date documentation. I had been trying to follow the documentation here https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-cordova-get-started
I will try to follow the documentation you pointed to and see if my luck changes. I'm not using VS. I can't imagine that's a show stopper. I'll post with successes or failures.

**Comment by bmourat** [comment] 2018-08-02 06:43
Hey @digish777 @wohlbier 
What version of ionic framework are you using?  Does this happen on all platforms?
And how do you  initialize `WindowsAzure` object?

**Comment by devShinobi** [comment] 2018-08-02 13:19
i am facing a similar issue on a cordova project made using visual studio 2017, cordova 6.3.1

**Comment by wohlbier** [comment] 2018-08-02 22:39
I tried to create a reproducer and capture it using script. I've attached the file "repro.txt". If you look at it using `less -r` all of the meta characters render properly. Also an image from ionic lab. Hopefully this helps get to the bottom of the issue.

[repro.txt](https://github.com/Azure/azure-mobile-apps-cordova-client/files/2255366/repro.txt)
<img width="888" alt="screen shot 2018-08-02 at 6 31 16 pm" src="https://user-images.githubusercontent.com/8867238/43614863-16acbd44-9683-11e8-85dc-c53123614ef0.png">

**Comment by bmourat** [comment] 2018-08-03 04:46
@wohlbier  thanks for the steps!
When running in a browser you should use `ionic cordova run browser` not `ionic serve` or `ionic lab`. See dicussion here https://github.com/Azure/azure-mobile-apps-cordova-client/issues/36. 
I see when you used command `ionic run browser` the error was `Cannot find name 'TodoItem'` because it was used without quotes.
Could you please try running it in a browser with `ionic cordova run browser` and see if it works like this?
Here is my app.component.ts
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { HomePage } from '../pages/home/home';
import { CommentStmt } from '../../node_modules/@angular/compiler';

declare var WindowsAzure: any;

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;
  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      var client = new WindowsAzure.MobileServiceClient("https://yoursite.azurewebsites.net");
      console.log(client);
      statusBar.styleDefault();
      splashScreen.hide();
      
    });
  }
}
```

**Comment by wohlbier** [comment] 2018-08-03 10:04
Thanks! I will try your program later today. I thought I had read about serve/lab/browser, but I wanted to do them all to get a confirmation from you. Regards the 'TodoItem' I realized that I was missing quotes. Near I changed it during the script session, so if you scroll past the error you saw you should see the error I got when the quotes were used. Thanks!

**Comment by wohlbier** [comment] 2018-08-03 10:31
It appears to run. I cannot tell if it connected properly. See attached. I also don't know where the console output goes.
[repro.txt](https://github.com/Azure/azure-mobile-apps-cordova-client/files/2257033/repro.txt)

**Comment by wohlbier** [comment] 2018-08-05 21:01
If I try to define and access WindowsAzure from a different typescript file within the application I get the undefined error:

`ERROR ReferenceError: WindowsAzure is not defined
    at PhantomPassLoginPage.webpackJsonp.190.PhantomPassLoginPage.navigateToConnectionsListPage (phantom-pass-login.ts:18)
    at Object.eval [as handleEvent] (PhantomPassLoginPage.html:38)
    at handleEvent (core.js:13589)
    at callWithDebugContext (core.js:15098)
    at Object.debugHandleEvent [as handleEvent] (core.js:14685)
    at dispatchEvent (core.js:10004)
    at core.js:10629
    at HTMLButtonElement.<anonymous> (platform-browser.js:2628)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)`

**Comment by bmourat** [comment] 2018-08-08 07:13
Hi @wohlbier 
How are calling it from other components? You need to be sure this line is called after platform ready event. I've tried calling it from another components constructor directly and it failed, after I placed it inside platform ready event handler, everything worked.

PS.
If you are using a browser, console output goes to standard console output which you can find in Developer tools of your browser. If you are running an Android app you can inspect your app with Chrome developer tools from `chrome://inspect` page.

**Comment by wohlbier** [comment] 2018-08-09 10:29
I have it in a platform ready, but it is not in the constructor. I declare WindowsAzure at global scope of the file. 

This is the code. Do you see anything stupid? Thanks!

`import { Component } from '@angular/core';
import { ConnectionsListPage } from '../connections-list/connections-list'
import { Platform, NavController } from 'ionic-angular';

declare var WindowsAzure: any;

@Component({
  selector: 'page-phantom-pass-login',
  templateUrl: 'phantom-pass-login.html'
})
export class PhantomPassLoginPage {
  constructor(
    public navCtrl: NavController,
    public platform: Platform
  )
  {
  }

  navigateToConnectionsListPage(): void {

    this.platform.ready().then(() => {

      var client = new WindowsAzure.MobileServiceClient(
        "https://jgwapp.azurewebsites.net"
      );
      console.log(client);
     // var todoTable = client.getTable('TodoItem');
    });
    this.navCtrl.push(ConnectionsListPage);
  }
}`


This is the error:

`core.js:1449 ERROR Error: Uncaught (in promise): ReferenceError: WindowsAzure is not defined
ReferenceError: WindowsAzure is not defined
    at phantom-pass-login.ts:21
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at phantom-pass-login.ts:21
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
    at HTMLButtonElement.v (polyfills.js:2)`

**Comment by bmourat** [comment] 2018-08-10 04:54
And when `navigateToConnectionsListPage`method is called?

**Comment by bmourat** [comment] 2018-08-10 12:07
Yes, i understand this, but who calls `navigateToConnectionsListPage`?

**Comment by wohlbier** [comment] 2018-08-11 16:34
Oh, sorry. I misunderstood you question. `navigateToConnectionsListPage` is called from the html below. The idea is that this would be a login page with authentication. I'm just trying to make contact with the server before handling authentication, of course.

```
<ion-content>

  <ion-grid>
    
    <ion-row><ion-col>
	<p><img align="middle" src="assets/imgs/PPLogo.png"></p>
    </ion-col></ion-row>
    
    <ion-row><ion-col>
	<h1>Login</h1>
    </ion-col></ion-row>
    
    <ion-row><ion-col>
	<ion-item>
	  <ion-label floating>Username</ion-label>
	  <ion-input type="text"></ion-input>
	</ion-item>
    </ion-col></ion-row>
    <ion-row><ion-col>
	<ion-item>
	  <ion-label floating>Password</ion-label>
	  <ion-input type="password"></ion-input>
	</ion-item>
    </ion-col></ion-row>
    
    <ion-row><ion-col text-center>
	<button ion-button color="primary"
		(click)="navigateToConnectionsListPage()">Sign In</button>
    </ion-col></ion-row>
  </ion-grid>

</ion-content>
```

**Comment by bmourat** [comment] 2018-08-13 04:57
That's very strange, the same setup works for me. Is this the whole file? Did you try to call it in a constructor?

**Comment by wohlbier** [comment] 2018-08-13 14:17
That is the whole file.

When I call it in the constructor I can get it to run without error, and in fact now sometimes I can get it to run without error in the function `navigateToConnectionsListPage`. However, in general I am having a very difficult time knowing if the browser platform is showing me the correct code. When I use `--live-reload` (actually, `-lc`) my changes almost never propagate to the browser instance. I see this in both chrome and firefox. Once in a while they changes do come through. It's incredibly frustrating.

If you look at the output below, which port should I use? 8000 or 8100? It seems like there is some live and/or cached version at either one and they behave differently. I've been clearing my browser cache, but that rarely helps.

```
[app-scripts] [09:58:00]  build dev finished in 8.18 s 
[app-scripts] [09:58:00]  watch ready in 8.22 s 

[INFO] Development server running!
       
       Local: http://localhost:8100
       External: http://147.81.44.154:8100
       
       Use Ctrl+C to quit this process

> cordova run browser
[cordova]  startPage = index.html
[cordova]  Static file server running @ http://localhost:8000/index.html
[cordova]  CTRL + C to shut down
```

More info:
```
collings:PhantomPass wohlbier$ ionic info
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.4, ios 4.5.4

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Comment by wohlbier** [comment] 2018-08-13 14:36
Ok, it looks like the code DOES NOT show the `ERROR Error: Uncaught (in promise): ReferenceError: WindowsAzure is not defined
ReferenceError: WindowsAzure is not defined` on `localhost:8000/index.html`, but DOES show the error on `localhost:8100/index.html`. However, `--live-reload` changes do not appear on 8000, but do appear on 8100. Is this expected?

**Comment by bmourat** [comment] 2018-08-14 05:04
I don't think this kind of behavior has something to do with the plugin, it is more Cordova-Ionic infrastructure question. As for me, I'm not using live-reload as I tend not to trust it) 
When I run this command `ionic cordova run browser -lc` i get this output:
```
07:50:34]  watch ready in 9.33 s 
[07:50:34]  dev server running: http://localhost:8100/ 

[OK] Development server running!
     Local: http://localhost:8100
     External: http://192.168.8.104:8100
     

> cordova run browser
startPage = index.html
Static file server running @ http://localhost:8001/index.html
CTRL + C to shut down
200 /index.html (gzip)

```
 and livereloading is not working also. I think the problem is that livereloading works only with `ionic serve` command. Also i found this thread https://github.com/ionic-team/ionic-cli/issues/790, maybe there is something you could use.

**Comment by bmourat** [comment] 2018-08-15 05:27
Hey @wohlbier,
If you don't have any questions, can I close this issue? You can reopen it anytime if you will stumble upon any issues.

**Comment by wohlbier** [comment] 2018-08-15 13:18
@bmourat that is fine with me. However, @digish777 is the one who opened the issue.

**Comment by bmourat** [comment] 2018-08-16 06:30
@digish777 

I'll close this issue, for now, if you have further questions, please feel free to reopen it.

Thanks,
Murat

**Closed by bmourat** 2018-08-16 06:30 UTC
